RAW_FOLDER : "./data/raw"  # location of raw data on local machine
INTERMEDIATE_FOLDER : "./data/intermediate"   # location of cleaned data on local machine
YF_INTERVAL : "1d" # yahoo finance API parameter "interval". Possible values: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo (optional, default is '1d')
USE_CACHED : False
END_DAY : "2022-03-23"  # ISO8601 format such as YYYY-MM-DD or YYYY-MM-DDTHH:mm:SS
NB_DAYS : 365  # number of days to extract
PARALLEL_DOWNLOAD : True # If True, all data are extracted simultaneously and gathered in same dataframe during download.

# Provide timezone according to pytz conventions. e.g. "UTC" or "Europe/Paris"
# Set to "null" to let as in original data
TIMEZONE_NEW_NAME : UTC

symbols:
  Tesla: TSLA
  Pfizer: PFE
  Hermès: RMS.PA
  Toyota: TM
  Tencent: TCEHY
  Rio Tinto: RIO
  Alphabet: GOOGL
  BMW: BMW.DE
  Dassault Systèmes: DSY.PA
  EDF: EDF.PA
  BTC-USD: BTC-USD