RAW_FOLDER : "./data/raw"
YF_INTERVAL : "1m" # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo (optional, default is '1d')
USE_CACHED : True
END_DAY : "2022-03-23"
symbols:
  - Tesla: TSLA
  - Pfizer: PFE
  - Hermès: RMS.PA
  - Toyota: TM
  - encent: TCEHY
  - Rio Tinto: RIO
  - Alphabet: GOOGL
  - BMW: BMWYY
  - Dassault Systèmes: DSY.PA
  - EDF: EDF.PA
  - BTC-USD: BTC-USD