RAW_FOLDER : "./data/raw"
INTERMEDIATE_FOLDER : "./data/intermediate"
YF_INTERVAL : "1m" # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo (optional, default is '1d')
USE_CACHED : True
END_DAY : "2022-03-23"  # ISO8601 format such as YYYY-MM-DD or YYYY-MM-DDTHH:mm:SS
NB_DAYS : 7  # number of days to extract
PARALLEL_DOWNLOAD : True
symbols:
  Tesla: TSLA
  Pfizer: PFE
  Hermès: RMS.PA
  Toyota: TM
  Tencent: TCEHY
  Rio Tinto: RIO
  Alphabet: GOOGL
  BMW: BMWYY
  Dassault Systèmes: DSY.PA
  EDF: EDF.PA
  BTC-USD: BTC-USD